// GET
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_ERROR = 'FETCH_QUESTION_ERROR';
// POST
export const FETCH_POST_QUESTION = 'FETCH_POST_QUESTION';
export const FETCH_POST_QUESTION_SUCCESS = 'FETCH_POST_QUESTION_SUCCESS';
export const FETCH_POST_QUESTION_ERROR = 'FETCH_POST_QUESTION_ERROR';
